# -*- coding: utf-8 -*-
"""01주차-숙제 2019117112_멘두요.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k7iU5mRrk061I-QOxGDlWoD8aumHWe5w

01주차: 컴퓨팅사고와 SW coding
2019117112_멘두요
"""

print(100 + 200)
print('100 + 200')
print(100, 200)
print('100', '200')
print('Hello', 'Python', '!')
print('Hello' + 'Python' + '!')
print('Hello''Python''!')
print('*' * 10)

print('Hello python!') #NameError: name 'Print' is not defined
print("Hello python!") #SyntaxError: EOL while scanning string literal
print('Hello Python!') #SyntaxError: invalid syntax
print('100' + '200') #TypeError: unsupported operand type(s) for +: 'int' and 'str'

print('50 + 30 =', 50 + 30)
print('50 - 30 =', 50 - 30)
print('50 * 30 =', 50 * 30)
print('50 / 30 =', 50 / 30)

side = int(input()) 
c = '*' 
for i in range(side):
    print((c*i).rjust(side-1)+c+(c*i).ljust(side-1))

def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n - 1)
print(factorial(3))
print(factorial(5))
print(factorial(12))
print(factorial(20))