# -*- coding: utf-8 -*-
"""02주차-LAB_숙제 2019117112_멘두요.ipynb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yur42sbe_ufll6ezeKnMK9cf533yO7oJ

##2주차
"""

##LAB 2-1
print('나의 이름은 :', '홍길동')
print('나의 나이는 :', 27)
print('나의 키는', 179, 'cm 입니다.')
print('10 + 20 =', 10 + 20)
print('10 * 20 =', 10 * 20)

##LAB 2-4
name = '전우치'
print('나의 이름은 :', name)

age = 27
print('나의 나이는 :', age)

height = 179
print('나의 키는', height, 'cm 입니다.')

sum = 10 + 20
print('10 + 20 =', sum)

mult = 10 * 20
print('10 * 20 =', mult)

##LAB 2-6
width = 20
height = 40
width = 30
area = width * height
print('사각형의 면적', area)

##LAB 2-7
a = 123 * 456
b = 1357 + 2468
c = 5 ** 4
d = 10 / 4
e = 10 // 5
f = 10 % 5
print("123 * 456 = {} \n1357 + 2468 = {} \n5 ** 4 = {} \n10 / 4 = {} \n10 // 5 = {} \n10 % 5 = {} \n ".format(a,b,c,d,e,f))


##LAB 2-7 /문제_2
a = 5 % 2
print("5를 2로 나눈 나머지는: ", a)


##LAB 2-7 /문제_3
a = 2 ** (1/2)
b = 3 ** (1/2)
print("2의 제곱근: {} \n3의 제곱근: {} \n ".format(a, b))

##LAB 2-8
a = 8 + 2j
b = 4 + 3j
print("a + b = {} \na - b = {} \na * b = {} \na / b = {} \n".format(a+b,a-b,a*b,a/b))

##LAB 2-10
name = input('이름을 입력하세요 : ')
print(name, '님이 입장하셨습니다.')

##LAB 2-10 /문제_2
m = int(input('숫자 m을 입력하세요 : '))
n = int(input('숫자 n을 입력하세요 : '))
print('m + n = {} \nm - n = {} \n'.format(m+n,m-n))