# -*- coding: utf-8 -*-
"""02주차_숙제_2019117112_멘두요.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/161EgNE5w7rDAtRNhWJyIobJHpuX1y9WL
"""

a = int(input('정사각형의 밑변을 입력하시오: '))
print('정사각형의 면적 : ', a*a )

a = int(input('섭씨온도를 입력하세요 : '))
print('섭씨',a,'도는 화씨', (a*9/5)+32, '도 입니다.' )

2 << 0 , 2 << 1 , 2 << 2 , 2 << 3 , 2 << 4 , 2 << 5 , 2 << 6 , 2 << 7 , 2 << 8 , 2 << 9

a = int(input(' 정수를 입력하세요 : '))
print(' 이 수가 짝수인가요? ' , a % 2 == 0 )

a = int(input('세 자리 정수를 입력하세요 : '))
print('백의 자리: ', a // 100)
print('십의 자리: ', a % 100 // 10)
print('일의 자리: ', a % 10)