# -*- coding: utf-8 -*-
"""03주차-숙제 2019117112_멘두요.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rX5soxUsoDxCu0SFngw1c0sSbb_xDkY6
"""

a, b, c = input("세 정수를 입력하시오 : ").split()
a = int(a)
b = int(b)
c = int(c)
if a > b:
    a, b = b, a
if b > c:
    b, c = c, b
if a > b:
    a, b = b, a   

print(a, b, c)

x, y = input("점의 좌표 x, y를 입력하시오 : ").split()
x = int(x)
y = int(y)
if x > 0 and y > 0:
  print("1사분면에 있음")
elif x < 0 and y > 0:
  print("2사분면에 있음")
elif x < 0 and y < 0:
  print("3사분면에 있음")
else:
  print("4사분면에 있음")

game_score = int(input('게임점수를 입룍하시오 : '))
if game_score > 1000:
  print("고수입니다.")
else:
  print("입문자입니다. ")

for i in range(3):
    print('Python ')
    print('is ')
    print('FUN! ')

for i in range(3):
    print('Python ')
    print('is ')
print('FUN! ')

n = int(input('숫자를 입력하세요 : '))
x = 0;

for i in range(2,n):
  if n%i == 0:
    x = 1

if x == 0:
  print(n, "는 소수입니다.")
else:
  print(n, "는 소수가 아닙니다.")

for n in range(100, 1000, 1):         
     num1 = n // 100
     num2 = (n%100) // 10
     num3 = ((n%100) % 10)

     number = (num1**3) + (num2**3) + (num3**3)  
 
     if(n == number ):            
         print( n )

num = int(input('1에서 9까지의 수를 입력하세요 : '))
while (num < 1 or num > 9):
  num = int(input('1에서 9까지의 수를 다시 입력하세요 : '))
for i in range(1, 10):
  print(num, "*", i, "=", num * i)

print("맛나 식당에 오신 것을 환영합니다. 메뉴는 다음과 같습니다. \n- 삼겹구이 (입력 s) \n- 오삼불고기 (입력 o) \n- 된장찌개 (입력 d) \n")
menu = input('메뉴를 선택하세요 (알파벳 s, o, d 입력) : ')
if menu == 's':
  print("삼겹구이를 선택하였습니다.")
elif menu == 'o':
  print("오삼불고기를 선택하였습니다.")
elif menu == 'd':
  print("된장찌개를 선택하였습니다.")
else:
  print("메뉴를 다시 입력하세요: ") 
  menu = input('메뉴를 선택하세요 (알파벳 s, o, d 입력) : ')
if menu == 's':
  print("삼겹구이를 선택하였습니다.")
elif menu == 'o':
  print("오삼불고기를 선택하였습니다.")
elif menu == 'd':
  print("된장찌개를 선택하였습니다.")

num = int(input('숫자를 입력하세요 : '))
for i in range(1, num+1):
  print(" "*(num-i), "*"*i)

n = int(input("n을 입력하시오: "))
arr = [[col+row*n for col in range(1, (n+1))] for row in range(n)]
if n < 10 and n > 0:
  for i in range(0, n):
    if i % 2 == 1:
        print(arr[i][::-1], end="")
    else:
        print(arr[i][::1], end="")
    print()