# -*- coding: utf-8 -*-
"""03주차-LAB_숙제 2019117112_멘두요.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pBIfFXWrbkDjM13pwpDDmIOBkmMb8Oo5
"""

##LAB 3-1 /문제_1
score = int(input("game_score = "))
if score > 1000:
  print("당신은 고수입니다.")

##LAB 3-1 /문제_2
a = int(input("num_a = "))
b = int(input("num_b = "))
if a > b:
  print("num_a가 더 많습니다.")
elif a == b:
  print("두 값이 일치합니다.")
else:
  print("num_b가 더 많습니다")

##LAB 3-2 /문제_1
n = int(input("정수를 입력하세요 : " ))
if n < 101 and n > 0:
  print("n =", n)
  if n % 2 == 0:
    print(n,"은(는) 짝수입니다.")

##LAB 3-2 /문제_2
x = int(input("정수를 입력하세요 : "))
if x < 101 and x > -101:
  print("x = ", x)
  if x > 0:
    print(x,"은/는 자연수입니다.")

##LAB 3-3 /문제_1
score = int(input("게임점수를 입력하세요 : "))
if score < 1000:
  print("game_score = {} \n입문자입니다.".format(score))
else:
  print("game_score = {} \n고수입니다.".format(score))

##LAB 3-3 /문제_2
x = int(input("한 정수를 입력하세요 : "))
y = int(input("다른 정수를 입력하세요: "))
if x > y and x < y:
  print("두 값이 일치하지 않습니다.")
else:
  print("두 값이 일치합니다.")

##LAB 3-3 /문제_3
a = str(input("당신은 성인인가요(성인이면 1, 미성년이면 0):"))
if a == '0':
  print("당신은 미성년자입니다.")
elif a == '1':
  s = input("결혼 하셨나요(기혼이면 1, 미혼이면 0):")
  if s == '0':
    print("당신은 결혼하지 않은 성인입니다.")
  if s == '1':
    print("당신은 결혼한성인입니다.")

##LAB 3-4 /문제_1
num = 2
if num < 10 and num > 1:
  print(True)
else:
  print(False)

##LAB 3-4 /문제_2
age = 12
if age > 10 and age < 19:
  print("age = {} \n청소년입니다".format(age))
else:
  print("age = {}".format(age))

##LAB 3-5
speed = int(input("자동차의 속도를 입력하세요(단위 : km/h):"))
if speed > 100:
  print("고속")
elif speed < 100 and speed > 60:
  print("중속")
else:
  print("저속")

##LAB 3-6 /문제_1
for i in range(5):
  print("Hello, Python!")

##LAB 3-6 /문제_2
for i in range(5):
  print(i)

##LAB 3-7 /문제_1
list(range(1,101))

##LAB 3-7 /문제_2
list(range(2, 101, 2))

##LAB /문제_3
list(range(1,100, 2))

##LAB 3-7 /문제_4
list(range(-99,0))

#LAB 3-8 /문제_1
s = 0
for i in range(1,101):
  s = s + i
  print('i = {}, s = {}'.format(i,s))

print("1에서 100까지의 합:",s)

##LAB 3-8 /문제_2
for i in range(2, 101, 2):
  print("1에서 100까지의 짝수:",i)

##LAB 3-8 /문제_3
for i in range(1,100,2):
  print("1에서 100까지의 홀수:",i)

##LAB 3-9
n = 7
for i in range(1,n+1):
  print(" " * (n-i), '#' )

